### ISSUE TITLE
[question] Return values types

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/ocaml-mem_usage#4]
## Summary
I think some of the return variables may not be correct, I'm not sure about that.

## Details
https://github.com/savonet/ocaml-mem_usage/blob/8a496f68268389b6d121a96c34b96c8ccbe6b0e0/lib/mem_usage.c#L145-L147

They are mainly `unsigned long`, but why `process_virtual_memory` and `process_physical_memory` are `long long`?

And then, the value is converted to `int`.
https://github.com/savonet/ocaml-mem_usage/blob/8a496f68268389b6d121a96c34b96c8ccbe6b0e0/lib/mem_usage.c#L189-L194

It looks like apple and windows have the same problem.

## Question
1. What will happen if I build and run it in 32-bit Linux?
   If I consume more than 2GB of memory, will it become negative?
1. Is the `val_int` size the same as `long int` in C?

**Comment by toots** [comment]
In C, `int` is always 2 bytes and `long` 4. In OCaml `int` is (signed)`31` bits on 32 bit platforms and (signed) `63` bits on 64 bits platforms. 

Your concern is indeed warranted. I just pushed a PR clarifying a couple of signed/`Val_long` conversions.

I am assuming that most platforms that run liquidsoap or this module at this point are 64 bits (yes, we need to gather more data but that seems reasonable). For these platforms `Val_int` is the same as `Val_long` and, so the chances of running into issues are very low.

**Comment by vitoyucepi** [comment]
As far as I know
In Linux x86, process memory is limited to 4GB, the same size as `unsigned long int` or 32 bits.
In Linux x86-64, process memory is limited by many GB, the same size as `unsigned long int` or 64 bits.

`Val_int` is 31(63) bit + sign. Are there any functions that support unsigned integers?

https://github.com/savonet/ocaml-mem_usage/blob/e100c5dffe03281d9107cfa96cd5b9fd77f652f5/lib/mem_usage.c#L145-L147


> `unsigned long long`

Why not `uint64_t`?

But what about sysinfo + pae?
```c
struct sysinfo {
               long uptime;             /* Seconds since boot */
               unsigned long loads[3];  /* 1, 5, and 15 minute load averages */
               unsigned long totalram;  /* Total usable main memory size */
               unsigned long freeram;   /* Available memory size */
               unsigned long sharedram; /* Amount of shared memory */
               unsigned long bufferram; /* Memory used by buffers */
               unsigned long totalswap; /* Total swap space size */
               unsigned long freeswap;  /* Swap space still available */
               unsigned short procs;    /* Number of current processes */
               unsigned long totalhigh; /* Total high memory size */
               unsigned long freehigh;  /* Available high memory size */
               unsigned int mem_unit;   /* Memory unit size in bytes */
               char _f[20-2*sizeof(long)-sizeof(int)];
                                        /* Padding to 64 bytes */
           };
```

**Comment by toots** [comment]
I was wrong regarding `int` and `long`, see: https://en.wikipedia.org/wiki/64-bit_computing

> In many programming environments for C and C-derived languages on 64-bit machines, int variables are still 32 bits wide, but long integers and pointers are 64 bits wide.

You can see the rest for more details. As such, using `long` should be fine in most cases.

Again, we're really trying to be right in most cases, which is 64 bit platforms with a reasonable amount of memory, i,.e. less than the maximum positive integer representable by a native OCaml integer of 63 bit size so something like `2^{62} bytes = 4194304 terabytes` I believe.

There are libraries for exact integer size in OCaml. `Int64` and `Int32` are part of the compiler API. [ocaml-integers](https://github.com/yallop/ocaml-integers) has most of the others. Currently, only `OCaml` integers are supported in liquidsoap. We could do more but, as of now, I believe for most use-case we should be fine with the native integers.

**Comment by vitoyucepi** [comment]
Don't these also should be `long` instead of `int`?
https://github.com/savonet/ocaml-mem_usage/blob/40b885b777b279bc099ce69ab3a7c2330aff90ba/lib/mem_usage.ml#L22-L29
and here too
https://github.com/savonet/ocaml-mem_usage/blob/40b885b777b279bc099ce69ab3a7c2330aff90ba/lib/mem_usage.mli#L22-L29

**Comment by toots** [comment]
Everything on OCaml that is type `int` is `63` bit on 64 bits platforms so we should be fine as well.
